name: CI
on: [push]
jobs:
  # test:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #   runs-on: ${{matrix.os}}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: goto-bus-stop/setup-zig@v1.2.1
  #       with:
  #         version: master
  #     - run: zig build test
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1.2.1
        with:
          version: master
      - run: zig fmt --check build.zig src